### ISSUE TITLE
Can't build on OS X

### ISSUE THREAD

**Issue by Rydgel** [MrMetric/block_thingy#1]
I doesn't seem to work with default clang:

```
In file included from /Users/xxx/Projects/C/block_thingy/src/graphics/OpenGL/ShaderProgram.hpp:21:
/Users/xxx/Projects/C/block_thingy/src/ResourceManager.hpp:4:10: fatal error: 
      'experimental/propagate_const' file not found
#include <experimental/propagate_const>
         ^
1 error generated.
make[2]: *** [CMakeFiles/block_thingy.dir/src/Camera.cpp.o] Error 1
```

**Comment by MrMetric** [comment]
What version of clang and libc++ are you using?

P.S. Sorry for not noticing this sooner! I wasn't expecting anyone to be posting issues this early in the project.

**Comment by Rydgel** [comment]
I am using the default clang on OS X:

```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
```

**Comment by MrMetric** [comment]
After some experimentation in a VM, I have fixed some problems with building on macOS (updated GLM, changed some syntax, fixed linking). Don't forget to update submodules after you pull!

It seems that Apple's Clang/libc++ is too old. I found that copying in libstdc++'s propagate_const works, but the filesystem library is missing, too. Installing LLVM with Homebrew provides a sufficiently recent version (4.0.1). Run CMake with `-DCMAKE_C_COMPILER=/usr/local/Cellar/llvm/4.0.1/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/Cellar/llvm/4.0.1/bin/clang++`.

If you try to build at this point, you will get an error from zstr (https://github.com/mateidavid/zstr/issues/5). Appending ` || defined(__APPLE__)` to line 30 fixes it.

Note: Since I am using a VM and I do not have GPU passthrough set up, I am unable to test running the engine. Please let me know if you encounter any problems!

**Comment by Rydgel** [comment]
Yeah it's working! I managed to compile it and run it.
It seems to not like the `line` shaders for some reason, so I had to comment the validate test function to be able to run it (at a slow framerate).

**Comment by MrMetric** [comment]
What error did you get about the shaders? And, what do you mean by 'the validate test function'? (you can post this as a new issue if you like)

If your framerate is low, you might be using a debug build. If you did not specify `-DCMAKE_BUILD_TYPE=release`, then that is the case.

**Comment by Rydgel** [comment]
I'll retry with a release build, but I had to comment this:

https://github.com/MrMetric/block_thingy/blob/master/src/graphics/OpenGL/ShaderProgram.cpp#L337-L344

Because otherwise I had a runtime exception. I was talking about the `glValidateProgram` function sorry. It seems to be related to the line shaders.

**Comment by MrMetric** [comment]
Please paste the error output. And, note that disabling that bit of code is a bad idea.
